### ISSUE TITLE
DEFAULT_PRIVATE

### ISSUE THREAD

**Issue by JoFo-IT** [roles-ansible/ansible_role_gitea#49]
I missing:

>DEFAULT_PRIVATE: last: Default private when creating a new repository. [last, private, public]

Can you add this point?

**Comment by DO1JLR** [comment]
Hi, thanks for the pull-request.

Did you know, that you can define other values like the "``DEFAULT_PRIVATE``" option in the ``[repository]`` section of the config file with the ``gitea_repository_extra_config`` variable?

Here is a example:
```yaml
gitea_repository_extra_config: |
  DEFAULT_PRIVATE = private
```

but since the pull request is now remembered, this is of course no longer necessary. :stuck_out_tongue_winking_eye:
