### ISSUE TITLE
backup on Upgrade is broken

### ISSUE THREAD

**Issue by jogrie** [roles-ansible/ansible_role_gitea#65]
when upgrading the backup functionality doesn't work

you can reproduce it with a fresh install
version '1.17.4'

after creating the admin user and a test repository switch to 'latest' and upgrade

my ansible version is 2.12.1
gitea host is a debian 11

TASK [do1jlr.gitea : Backing up gitea before upgrade] ****************************************************************************************************************************************************************************************************************************************************************
fatal: [vboxdeb11]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: Ungültiger Modus: „A+user:gitea:rx:allow“\n„chmod --help“ liefert weitere Informationen.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user"}

**Comment by DO1JLR** [comment]
RESOLVED in #66

**Comment by JensTimmerman** [comment]
I believe the solution in #66 is a bad way to go about this, there should be no reason to make gitea run as root because your ansible is not correctly configured to work with become, the documentation in https://docs.ansible.com/ansible-core/2.12/user_guide/become.html#risks-of-becoming-an-unprivileged-user%22%7D explains the risks of doing privilege escalation, but in this case we were actually doing privilige deescalation by using become. Which has less risks, running gitea as root has risks!

**Comment by JensTimmerman** [comment]
@jogrie I think you should look at trying to fix your ansible installation, e.g, look at recommendations in https://github.com/georchestra/ansible/issues/55
e.g. installing the acl package.

I'm sure running things as root will fix the issue, but it is not the secure way of doing things and has inherent risks.
