### ISSUE TITLE
Container Registry support?

### ISSUE THREAD

**Issue by niccolox** [roles-ansible/ansible_role_gitea#73]
hello

does this role currently allow gitea Docker "Container Registry" as recently submitted in this PR? 

https://docs.gitea.io/en-us/packages/container/
https://github.com/go-gitea/gitea/pull/16510

**Comment by niccolox** [comment]
looks like the docs are ahead of the releases

v1.17 possibly?
https://discourse.gitea.io/t/github-packages-equivalent/2901/2

**Comment by DO1JLR** [comment]
Container regestry support in gitea sounds like a cool feature.

By just looking at the pull request and the container regestry doc I'm not quite sure what it takes in gitea to use this. The way I currently interpret this config file, it seems that you just have to set a config value to true or false for container regestry support once version 1.17 of gitea is released.

See https://github.com/KN4CK3R/gitea/blob/16f8940b37a224592e46c5fa9d60b2ed6d4a5496/custom/conf/app.example.ini#L2248-L2250

If this is the case, then this is currently already supported with the ansible role here. Since you can configure variables that are not defined by the ``*_extra_config`` parameter.
A possible configuration could look like this:

```yaml
gitea_extra_config:  |
  [packages]
  ENABLED = true
```

As soon as there is a gitea version with container support, we can also include the most important variables in ansible. But I would wait until the actual release.

**Comment by niccolox** [comment]
yes, the fact Gitea added the documentation for the feature makes me optimistic it will be released sooner than later

**Comment by DO1JLR** [comment]
BTW,  Package Registry support is nativ built in in gitea and enabled by default.
Since https://github.com/roles-ansible/ansible_role_gitea/releases/tag/v3.0.0 there are some variables available to modify or disable it.
